# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transformations.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Transformations(object):
    def setupUi(self, MainWindow, currentObject: str, updateObject, controller, closeModal):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(359, 516)
        self.currentObject = currentObject
        self.updateObject = updateObject
        self.closeModal = closeModal
        self.controller = controller
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(6, 2, 321, 31))
        self.labelName.setObjectName("labelName")
        self.labelName.setText(self.currentObject.name)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 40, 341, 381))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(4, 1, 91, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.translationRadioButton = QtWidgets.QRadioButton(self.widget)
        self.translationRadioButton.setObjectName("translationRadioButton")
        self.verticalLayout.addWidget(self.translationRadioButton)
        self.scalingRadioButton = QtWidgets.QRadioButton(self.widget)
        self.scalingRadioButton.setObjectName("scalingRadioButton")
        self.verticalLayout.addWidget(self.scalingRadioButton)
        self.rotationRadioButton = QtWidgets.QRadioButton(self.widget)
        self.rotationRadioButton.setObjectName("rotationRadioButton")
        self.verticalLayout.addWidget(self.rotationRadioButton)
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setGeometry(QtCore.QRect(100, 10, 211, 241))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.widget2 = QtWidgets.QWidget(self.frame)
        self.widget2.setGeometry(QtCore.QRect(0, 290, 220, 77))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioAroundWorld = QtWidgets.QRadioButton(self.widget2)
        self.radioAroundWorld.setObjectName("radioAroundWorld")
        self.verticalLayout_3.addWidget(self.radioAroundWorld)
        self.radioAroundObjectCenter = QtWidgets.QRadioButton(self.widget2)
        self.radioAroundObjectCenter.setObjectName("radioAroundObjectCenter")
        self.verticalLayout_3.addWidget(self.radioAroundObjectCenter)
        self.radioAnyPoint = QtWidgets.QRadioButton(self.widget2)
        self.radioAnyPoint.setObjectName("radioAnyPoint")
        self.verticalLayout_3.addWidget(self.radioAnyPoint)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(80, 430, 178, 30))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.confirmTransformButton = QtWidgets.QPushButton(self.widget3)
        self.confirmTransformButton.setObjectName("confirmTransformButton")
        self.confirmTransformButton.clicked.connect(self.confirmTransformation)
        self.horizontalLayout_5.addWidget(self.confirmTransformButton)
        self.resetTransformButton = QtWidgets.QPushButton(self.widget3)
        self.resetTransformButton.setObjectName("resetTransformButton")
        self.resetTransformButton.clicked.connect(self.closeModal)
        self.horizontalLayout_5.addWidget(self.resetTransformButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 359, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.translationRadioButton.setText(_translate("MainWindow", "Translação"))
        self.scalingRadioButton.setText(_translate("MainWindow", "Escala"))
        self.rotationRadioButton.setText(_translate("MainWindow", "Rotação"))
        self.label.setText(_translate("MainWindow", "x"))
        self.label_2.setText(_translate("MainWindow", "y"))
        self.label_6.setText(_translate("MainWindow", "x"))
        self.label_7.setText(_translate("MainWindow", "y"))
        self.label_3.setText(_translate("MainWindow", "Graus"))
        self.radioAroundWorld.setText(_translate("MainWindow", "Em torno do mundo"))
        self.radioAroundObjectCenter.setText(_translate("MainWindow", "Em torno do centro do objeto"))
        self.radioAnyPoint.setText(_translate("MainWindow", "Em torno de um ponto qualquer"))
        self.confirmTransformButton.setText(_translate("MainWindow", "Confirmar"))
        self.resetTransformButton.setText(_translate("MainWindow", "Cancelar"))




    def confirmTransformation(self):
        transformData = {}

        transformData['object'] = self.currentObject
        if self.translationRadioButton.isChecked():
            transformData['type'] = 'translation'
            transformData['tx'] = self.lineEdit.text()
            transformData['ty'] = self.lineEdit_2.text()

        elif self.scalingRadioButton.isChecked():
            transformData['type'] = 'scaling'
            transformData['sx'] = self.lineEdit_4.text()
            transformData['sy'] = self.lineEdit_5.text()

        elif self.rotationRadioButton.isChecked():
            transformData['type'] = 'rotation'
            transformData['angle'] = self.lineEdit_3.text()

        if self.radioAroundWorld.isChecked():
            transformData['center'] = 'origin'
        elif self.radioAroundObjectCenter.isChecked():
            transformData['center'] = 'object'
        elif self.radioAnyPoint.isChecked():
            transformData['center'] = 'point'

        self.controller.transformObject(self.currentObject.name, transformData)
        self.closeModal()